import json
import time
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.core.session import SessionState

from src.utils import logger

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>MeshBreaker Report — {session_id}</title>
<style>
  body {{ font-family: 'Segoe UI', monospace; background: #0d0d0d; color: #e0e0e0; padding: 2rem; }}
  h1 {{ color: #00d4ff; }} h2 {{ color: #00a0cc; border-bottom: 1px solid #333; padding-bottom: .3em; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 1.5rem; }}
  th {{ background: #1a1a2e; color: #00d4ff; padding: .5rem 1rem; text-align: left; }}
  td {{ padding: .4rem 1rem; border-bottom: 1px solid #1e1e1e; }}
  tr:hover {{ background: #111; }}
  .critical {{ color: #ff4444; font-weight: bold; }}
  .high {{ color: #ff7700; }}
  .medium {{ color: #ffcc00; }}
  .low {{ color: #88cc44; }}
  pre {{ background: #111; padding: 1rem; overflow-x: auto; border-radius: 4px; font-size: .85em; }}
  .badge {{ padding: .15em .5em; border-radius: 3px; font-size: .8em; }}
  .badge-mesh {{ background: #003355; color: #44aaff; }}
</style>
</head>
<body>
<h1>MeshBreaker Security Report</h1>
<p>Session: <code>{session_id}</code> &nbsp;|&nbsp; Generated: {timestamp}</p>

{body}

<hr><p style="color:#555;font-size:.8em">Generated by MeshBreaker — For authorized security research only.</p>
</body>
</html>"""


class ReportGenerator:
    def __init__(self, session: "SessionState"):
        self.session = session
        self._ts = time.strftime("%Y-%m-%d %H:%M:%S")

    def generate(self, fmt: str, output_dir=None) -> str:
        """Write a single format and return its path.

        `fmt` is md, markdown, html or json.
        """
        writers = {
            "json":     ("json", self._write_json),
            "md":       ("md",   self._write_markdown),
            "markdown": ("md",   self._write_markdown),
            "html":     ("html", self._write_html),
        }
        key = fmt.lower()
        if key not in writers:
            raise ValueError(f"Unknown report format: {fmt} (use md, html or json)")

        extension, writer = writers[key]
        dest = Path(output_dir or self.session.output_dir) / "reports"
        dest.mkdir(parents=True, exist_ok=True)
        path = str(dest / f"report_{self.session.session_id}.{extension}")

        writer(path)
        logger.success(f"Report written → {path}")
        return path

    def generate_all(self, output_dir=None):
        dest = Path(output_dir or self.session.output_dir) / "reports"
        dest.mkdir(parents=True, exist_ok=True)
        sid = self.session.session_id

        paths = {
            "json":     str(dest / f"report_{sid}.json"),
            "markdown": str(dest / f"report_{sid}.md"),
            "html":     str(dest / f"report_{sid}.html"),
        }

        self._write_json(paths["json"])
        self._write_markdown(paths["markdown"])
        self._write_html(paths["html"])

        logger.success(f"Reports written to {dest}/")
        for fmt, path in paths.items():
            logger.info(f"  {fmt.upper():8} → {path}")
        return paths

    def _write_json(self, path):
        report = {
            "session_id":   self.session.session_id,
            "generated":    self._ts,
            "target_mac":   self.session.target_mac,
            "target_ip":    self.session.target_ip,
            "mesh_protocol": self.session.mesh_protocol,
            "devices_found": len(self.session.devices),
            "results":       self.session.results,
        }
        with open(path, "w") as f:
            json.dump(report, f, indent=2, default=str)

    def _write_markdown(self, path):
        lines = [
            "# MeshBreaker Security Report\n",
            f"**Session:** `{self.session.session_id}`  ",
            f"**Generated:** {self._ts}  \n",
            "---\n",
            "## Target",
            f"- **MAC:** `{self.session.target_mac or 'N/A'}`",
            f"- **IP:** `{self.session.target_ip or 'N/A'}`",
            f"- **Protocol:** `{self.session.mesh_protocol or 'unknown'}`",
            f"- **Devices found:** {len(self.session.devices)}\n",
            "---\n",
        ]

        cve_results = self.session.get("cve_check", [])
        if cve_results:
            lines.append("## CVE Matches\n")
            lines.append("| CVE | Severity | CVSS | Name | Matched on |")
            lines.append("|-----|----------|------|------|------------|")
            for m in cve_results:
                cve_id = m.get("cve_id", "") if isinstance(m, dict) else m.cve_id
                name   = m.get("name", "")   if isinstance(m, dict) else m.name
                sev    = m.get("severity","") if isinstance(m, dict) else m.severity
                cvss   = m.get("cvss","")     if isinstance(m, dict) else m.cvss
                mo     = m.get("matched_on",[]) if isinstance(m, dict) else m.matched_on
                lines.append(f"| {cve_id} | **{sev}** | {cvss} | {name} | {'; '.join(mo[:2])} |")
            lines.append("")

        proto_results = self.session.get("protocol_id", [])
        if proto_results:
            lines.append("## Protocol Identification\n")
            for p in proto_results:
                name = p.get("name","") if isinstance(p, dict) else p.name
                conf = p.get("confidence",0) if isinstance(p, dict) else p.confidence
                ev   = p.get("evidence",[])  if isinstance(p, dict) else p.evidence
                lines.append(f"- **{name}** — confidence {conf}%")
                for e in ev[:3]:
                    lines.append(f"  - {e}")
            lines.append("")

        fw = self.session.get("firmware")
        if fw:
            lines.append("## Firmware Analysis\n")
            info = fw if isinstance(fw, dict) else fw.__dict__
            for k, v in info.items():
                if k in ("strings", "raw_samples"):
                    continue
                lines.append(f"- **{k}:** `{v}`")
            lines.append("")

        gatt = self.session.get("gatt")
        if gatt:
            lines.append("## GATT Enumeration\n")
            surface = gatt.get("attack_surface", []) if isinstance(gatt, dict) else []
            if surface:
                lines.append(f"**Attack surface ({len(surface)} writable characteristics):**\n")
                for item in surface:
                    lines.append(f"- `{item.get('uuid')}` handle `{item.get('handle', 0):#06x}`")
            lines.append("")

        prov_cap  = self.session.get("provisioning_capture", {})
        prov_gatt = self.session.get("provisioning_gatt", {})
        if prov_cap or prov_gatt:
            lines.append("## Provisioning Security\n")
            if prov_cap:
                lines.append(f"- PB-ADV sessions observed: {prov_cap.get('sessions', 0)}")
            if prov_gatt:
                exposed = prov_gatt.get("provisioning_service")
                lines.append(f"- PB-GATT provisioning service exposed: "
                             f"**{'yes' if exposed else 'no'}**")
                lines.append(f"- Mesh Proxy service present: "
                             f"{'yes' if prov_gatt.get('proxy_service') else 'no'}")
            findings = list(prov_cap.get("findings", [])) + list(prov_gatt.get("findings", []))
            if findings:
                lines.append("")
                for f in findings:
                    cve = f" ({f['cve']})" if f.get("cve") else ""
                    lines.append(f"- **{f.get('severity')}** — {f.get('title')}{cve}")
                    lines.append(f"  - {f.get('detail')}")
            lines.append("")

        df = self.session.get("directed_forwarding", {})
        if df:
            lines.append("## Directed Forwarding (Mesh 1.1)\n")
            lines.append(f"- Detected: **{'yes' if df.get('present') else 'no'}** "
                         f"(confidence {df.get('confidence', 0)}%)")
            for e in df.get("evidence", []):
                lines.append(f"  - {e}")
            models = df.get("models", {})
            if models:
                lines.append("- Mesh 1.1 models found:")
                for mid, name in models.items():
                    lines.append(f"  - `{mid}` {name}")
            for f in df.get("findings", []):
                lines.append(f"- **{f.get('severity')}** — {f.get('title')}")
                lines.append(f"  - {f.get('detail')}")
                if f.get("reference"):
                    lines.append(f"  - *Reference: {f['reference']}*")
            lines.append("")

        follow = self.session.get("connection_follow", {})
        if follow:
            lines.append("## Connection Following\n")
            lines.append(f"- Access Address: `{follow.get('access_address')}`")
            lines.append(f"- CRCInit: `{follow.get('crc_init')}`")
            lines.append(f"- Hop increment: {follow.get('hop_increment')} "
                         f"(algorithm {follow.get('algorithm')})")
            lines.append(f"- Connection interval: {follow.get('interval_ms')} ms")
            lines.append(f"- Channels in use: {follow.get('channels_used')} / 37")
            channels = follow.get("predicted_channels", [])
            if channels:
                lines.append(f"- Predicted channel sequence: "
                             f"`{' '.join(str(c) for c in channels[:20])}`")
            lines.append("")

        fuzz = self.session.get("mesh_fuzz", [])
        if fuzz:
            crashes = [r for r in fuzz if (r.get("crashed") if isinstance(r,dict) else r.crashed)]
            lines.append(f"## Mesh Fuzz Results\n")
            lines.append(f"- Payloads sent: {len(fuzz)}")
            lines.append(f"- **Crashes detected: {len(crashes)}**\n")
            for c in crashes:
                strat = c.get("strategy","") if isinstance(c,dict) else c.strategy
                pl    = c.get("payload","")  if isinstance(c,dict) else c.payload.hex()
                lines.append(f"  - Strategy `{strat}`: `{pl}`")
            lines.append("")

        lines += ["---\n", "*Generated by MeshBreaker — For authorized security research only.*\n"]
        Path(path).write_text("\n".join(lines))

    def _write_html(self, path):
        body_parts = []

        body_parts.append("<h2>Target Summary</h2>")
        body_parts.append("<table><tr><th>Field</th><th>Value</th></tr>")
        for k, v in [("MAC", self.session.target_mac), ("IP", self.session.target_ip),
                     ("Protocol", self.session.mesh_protocol),
                     ("Devices found", len(self.session.devices))]:
            body_parts.append(f"<tr><td>{k}</td><td><code>{v or 'N/A'}</code></td></tr>")
        body_parts.append("</table>")

        cve_results = self.session.get("cve_check", [])
        if cve_results:
            body_parts.append("<h2>CVE Matches</h2>")
            body_parts.append("<table><tr><th>CVE</th><th>Sev</th><th>CVSS</th><th>Name</th><th>Matched on</th></tr>")
            for m in cve_results:
                cve_id = m.get("cve_id","") if isinstance(m,dict) else m.cve_id
                sev    = m.get("severity","") if isinstance(m,dict) else m.severity
                cvss   = m.get("cvss","")     if isinstance(m,dict) else m.cvss
                name   = m.get("name","")     if isinstance(m,dict) else m.name
                mo     = m.get("matched_on",[]) if isinstance(m,dict) else m.matched_on
                cls    = sev.lower() if sev.lower() in ("critical","high","medium","low") else ""
                body_parts.append(
                    f"<tr><td>{cve_id}</td><td class='{cls}'>{sev}</td>"
                    f"<td>{cvss}</td><td>{name}</td><td>{'; '.join(mo[:2])}</td></tr>"
                )
            body_parts.append("</table>")

        html = _HTML_TEMPLATE.format(
            session_id=self.session.session_id,
            timestamp=self._ts,
            body="\n".join(body_parts),
        )
        Path(path).write_text(html)
